- paranamer/src/test/java/com/fasterxml/jackson/module/paranamer/TestCreatorWithNamingStrategy.java
This is a simplified test that is causing the Scala module to be incompatible with Dropwizard's Duration and et all (FasterXML/jackson-module-scala#229). 
This test passes if you remove the `registerModule(new ParnamerModule())`. The only piece of the module required to trigger this issue is the `ParanamerAnnotationIntrospector`.
It fails inside of `BeanDeserializerFactory` because it cannot find `Delimited` as a constructor argument (it's not, it's an argument of the creator).
```
com.fasterxml.jackson.databind.JsonMappingException: Could not find creator property with name 'Delimited' (in class com.fasterxml.jackson.module.paranamer.TestCreatorWithNamingStrategy$StaticStringCreatorBean)
at [Source: "42|NotMyRealName"; line: 1, column: 1]
at …
```
> Add failing test with static string creator using paranamer.

- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/ser/PropertyAccessorCollector.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/deser/TestSimpleDeserialize.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/ser/TestSimpleSerialize.java
Hi,
Thank you for the great software! I learned a lot about asm!
But one thing I noticed that generated serializer/deserializer uses same name. So if the binary check sum is matched, it might be a problem so I made a small changes in order to use different name.
Thank you
> Fixed typo of generated serializer name

- guice/pom.xml
There were [many changes in Guice 4.0](http://google.github.io/guice/api-docs/4.0/api-diffs/changes.html). But all interfaces actually used in jackson-module-guice are still compatible between Guice 3.0 and Guice 4.1.
[Changes of Guice 4.1](http://google.github.io/guice/api-docs/4.1/api-diffs/changes.html) were conservative. I think that it is reasonable to expand range from `4.0]` to `5.0)`.
It might be better that README.md recommends users to specify a fixed version of Guice as well as dependency to jackson-module-guice in application's pom.xml file.
> Allowing Guice 4.x series

- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/deser/CreatorOptimizer.java
When using INVOKEVIRTUAL the first parameter needs to be the internal class
name (i.e. com/fasterxml/x/y/SomeClass) not the type descriptor
(Lcom/fasterxml/x/y/Class;) and some classloaders are more strict about this
than others it seems.
Resolves https://github.com/FasterXML/jackson-module-afterburner/issues/68
> Fix incorrect class name use in Afterburner.

- afterburner/pom.xml
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/deser/CreatorOptimizer.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/deser/PropertyMutatorCollector.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/ser/PropertyAccessorCollector.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/DynamicPropertyAccessorBase.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/bytebuddy/AbstractCreateLocalVarStackManipulation.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/bytebuddy/AbstractDelegatingAppender.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/bytebuddy/AbstractPropertyStackManipulation.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/bytebuddy/ConstructorCallStackManipulation.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/bytebuddy/GenerateIllegalPropertyCountExceptionStackManipulation.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/bytebuddy/JumpStackManipulation.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/bytebuddy/SimpleExceptionHandler.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/bytebuddy/SinglePropStackManipulationSupplier.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/bytebuddy/TableSwitchStackManipulation.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/bytebuddy/UsingIfStackManipulation.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/bytebuddy/UsingSwitchStackManipulation.java
- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/util/bytebuddy/VisitLabelStackManipulation.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/deser/TestCreators.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/deser/TestSingleArgCtors.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/ser/TestSimpleSerialize.java
This PR replaces all the parts that contain ASM code-gen logic, with ByteBuddy.
I should note that while replacing the ASM code-gen code with the relevant ByteBuddy code, I tried to encapsulate the common logic and "algorithms" of the various parts into self standing classes that can be composed and reused.
Furthermore, the new code also contains a few minor changes to the generated bytecode in order to remove the following unnecessary instructions:
- When generating code for a single method/field, the index is no longer loaded onto the stack since it's not used
- The IllegalArgumentException is only generated when using the `switch` method. In the case of a single method/field or when the `if` method is used, the exceptions are not generated since it was impossible for control to reach …
> Replace ASM code-gen with ByteBuddy in afterburner

- afterburner/README.md
- guice/README.md
- jaxb/README.md
- mrbean/README.md
- osgi/README.md
- paranamer/README.md
OpenShit Online V2 is closed and this domain is not accessible anymore.
And javadoc.io introduce badges hosted directly on javadoc.io
> Update URL for Javadoc badge's image

- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/deser/OptimizedSettableBeanProperty.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/deser/struct/ScalarCoercionTest.java
Fixes #69 
This fix is for 2.9, but it should merge without conflicts into 2.10 as well.
> Only coerce scalars if ALLOW_COERCION_OF_SCALARS is enabled

- mrbean/pom.xml
- mrbean/src/main/java/com/fasterxml/jackson/module/mrbean/BeanBuilder.java
- mrbean/src/test/java/com/fasterxml/jackson/module/mrbean/TestAbstractClasses.java
- mrbean/src/test/java/com/fasterxml/jackson/module/mrbean/TestAbstractClassesWithOverrides.java
- mrbean/src/test/java/com/fasterxml/jackson/module/mrbean/TestSimpleMaterializedInterfaces.java
This PR is equivalent to #102 but targets `2.11` instead.  The fix (if you wish to cherry-pick separately) is in https://github.com/FasterXML/jackson-modules-base/commit/e0bfe3fcca4748a4ed12906447df072243e392bb.
When the type to materialize extends/implements some interface that has a `default` method implementation (with a non-bean method name), MrBean will treat the method as if it lacks an implementation.
Use `Class.getMethod` to locate the exact method that the implemented type will utilize, which properly handles this case.
I've added several unit tests to cover the fixed behavior, and to verify existing, related behavior:
1. `TestSimpleMaterializedInterfaces.testInheritedDefaultMethodInInterface` is the test case that exercise the current issue, which is now resolved.
2. …
> MrBean: Fix detection of inherited default method in Java 8+ interface

- mrbean/src/main/java/com/fasterxml/jackson/module/mrbean/BeanBuilder.java
- mrbean/src/test/java/com/fasterxml/jackson/module/mrbean/TestAbstractClassesWithOverrides.java
This builds on #109 to verify and fix the behavior of checking re-abstracted methods for concreteness.
When searching for a concrete override, the existing logic will skip over methods in subclasses that are marked abstract.  If such a method is an override for a concrete method in a parent class, then the logic will incorrectly search the parent class where it will find the concrete method and it will incorrectly return true from `hasConcreteOverride`.  
This behavior has the following undesirable outcomes, depending on the `FAIL_ON_UNMATERIALIZED_METHOD` setting:
1. When disabled, then subsequent invocation of the re-abstracted method will throw an AbstractMethodError, rather than an UnsupportedOperationException.
2. When enabled, then the re-abstracted method will incorrectly NOT fail …
> MrBean: Correct handling of re-abstracted methods

- guice/src/moditect/module-info.java
- jaxb/src/moditect/module-info.java
Module-Info Enhancements - Support JAXB for Jakarta Release
https://github.com/FasterXML/jackson-databind/issues/2910
Support the namespaces specified for JAXB in Jakarta, as well as make activation dependent on the client implementation for javax or jakarta
> Module-Info Enhancements - Support JAXB for Jakarta Release

- blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/deser/BBDeserializerModifier.java
- blackbird/src/test/java/com/fasterxml/jackson/module/blackbird/deser/BasicDeserialize123Test.java
> Blackbird: correct methodType for setters that take arguments that aren't Objects

- jaxb/src/test/java/com/fasterxml/jackson/module/jaxb/introspect/TestPropertyVisibility.java
Fixed flaky test `testNoneAccessWithXmlElements`
The test `testNoneAccessWithXmlElements` compares the result of `MAPPER.writeValueAsString(input)` with a hardcoded string. However, the function `com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString()` would not always return JSON properties in the same order.
> fix flaky test testNoneAccessWithXmlElements

- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/AfterburnerTestBase.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/deser/TestIssue14.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/deser/jdk/JDKScalarsDeserTest.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/format/MapFormatShapeTest.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/ser/TestInclusionAnnotations.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/ser/TestJsonFilter.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/ser/TestStdSerializerOverrides.java
- blackbird/src/test/java/com/fasterxml/jackson/module/blackbird/BlackbirdTestBase.java
- blackbird/src/test/java/com/fasterxml/jackson/module/blackbird/deser/TestIssue14.java
- blackbird/src/test/java/com/fasterxml/jackson/module/blackbird/format/MapFormatShapeTest.java
- blackbird/src/test/java/com/fasterxml/jackson/module/blackbird/ser/TestInclusionAnnotations.java
- blackbird/src/test/java/com/fasterxml/jackson/module/blackbird/ser/TestJsonFilter.java
- blackbird/src/test/java/com/fasterxml/jackson/module/blackbird/ser/TestStdSerializerOverrides.java
Fix 14 flaky tests using annotations and linkedhashmap. Mirror tests in blackbird module are also fixed. A ﬂaky test is an analysis of web application code that fails to produce the same result each time the same analysis is run. Flaky tests are detected by nondex (https://github.com/TestingResearchIllinois/NonDex) which is tool developped by the research group led by professor Darko at UIUC.
1.com.fasterxml.jackson.module.afterburner.deser.jdk.JDKScalarsDeserTest.testNullForPrimitivesNotAllowedMisc
2. com.fasterxml.jackson.module.afterburner.deser.TestIssue14.testIssue
3. com.fasterxml.jackson.module.afterburner.ser.TestInclusionAnnotations.testIncludeUsingAnnotation
4. com.fasterxml.jackson.module.afterburner.ser.TestJsonFilter.testMissingFilter
5. …
> Fix 14 flaky tests in afterburner and blackbird module

- blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java
If blackbird attempts to access/define a new class concurrently,
it can hit a race condition between attempting to access it and
defining it when that fails.  If it does fail, enter a synchronized
block and try again before defining the access class.
Should fix #169
> Synchronize the lookup-and-define-class logic in blackbird

- blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/CrossLoaderAccess.java
If blackbird attempts to access/define a new class concurrently,
it can hit a race condition between attempting to access it and
defining it when that fails.  If it does fail, enter a synchronized
block and try again before defining the access class.
Should fix #169
> Synchronize the lookup-and-define-class logic in blackbird (2.13 cherry pick of #172)

- jakarta-xmlbind/pom.xml
- jakarta-xmlbind/src/main/java/com/fasterxml/jackson/module/jakarta/xmlbind/JakartaXmlBindAnnotationIntrospector.java
- jakarta-xmlbind/src/main/java/com/fasterxml/jackson/module/jakarta/xmlbind/deser/DataHandlerDeserializer.java
- jakarta-xmlbind/src/main/java/com/fasterxml/jackson/module/jakarta/xmlbind/ser/DataHandlerSerializer.java
Upstream is #176, however this one is a bit different. #152 seemed to partially solve this, but never changed the package names. I noticed it imports the implementation too instead of the API, which might be required but I'm not sure. The 2.13 won't currently compile without this change.
Let me know if the API vs the implementation is preferred and I can either change this PR or the upstream #176 one.
> [issue172] Migrate to a Jakarta namespaced activation API.

- jakarta-xmlbind/pom.xml
- jaxb/pom.xml
* this appears wrong and I checked the 2.15.0-SNAPSHOT jars to validate that the module-info.class ends up in versions/11 instead of versions/9
* https://github.com/FasterXML/jackson-modules-base/issues/126
> jaxb and jakarta-xmlbind put module-info in versions/11

- README.md
- guice7/README.md
- guice7/pom.xml
- guice7/src/main/java/com/fasterxml/jackson/module/guice7/GuiceAnnotationIntrospector.java
- guice7/src/main/java/com/fasterxml/jackson/module/guice7/GuiceInjectableValues.java
- guice7/src/main/java/com/fasterxml/jackson/module/guice7/ObjectMapperModule.java
- guice7/src/main/java/com/fasterxml/jackson/module/guice7/PackageVersion.java.in
- guice7/src/main/resources/META-INF/LICENSE
- guice7/src/main/resources/META-INF/NOTICE
- guice7/src/moditect/module-info.java
- guice7/src/test/java/com/fasterxml/jackson/module/guice7/Ann.java
- guice7/src/test/java/com/fasterxml/jackson/module/guice7/ExtendInjectableTest.java
- guice7/src/test/java/com/fasterxml/jackson/module/guice7/ObjectMapperModuleTest.java
- pom.xml
Copy guice (javax.inject) module over to a new guice 7 (jakarta.inject) module.  Replace javax imports with jakarta imports, and leave everything else the same.
Fixes #206
> Add guice7 (jakarta.inject) module

- jakarta-xmlbind/src/main/java/com/fasterxml/jackson/module/jakarta/xmlbind/JakartaXmlBindAnnotationIntrospector.java
- jaxb/src/main/java/com/fasterxml/jackson/module/jaxb/JaxbAnnotationIntrospector.java
> Fix regression for JAXB annotations by implementing `findEnumValues(MapperConfig, AnnotatedClass, Enum[], String[])`

- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/AfterburnerModule.java
- blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/BlackbirdModule.java
> Blackbird, Afterburner: disable in native-image

- afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/AfterburnerModule.java
- blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/BlackbirdModule.java
Seems like the `TODO:` was written before exposing `NativeImageUtil.isRunningInNativeImage()` in `databind` by https://github.com/FasterXML/jackson-databind/pull/4060
> Follow up wrt #191 by using `NativeImageUtil.isRunningInNativeImage()` in `databind`

- jakarta-xmlbind/pom.xml
- release-notes/CREDITS-2.x
- release-notes/VERSION-2.x
Note: replaces #221 which fails on CI (not due to PR)
> Fix #219: relax jakarta.xml.bind OSGI version dependency

- jaxb/pom.xml
Reverts FasterXML/jackson-modules-base#235
Not sure what on earth happened -- this got somehow merged into 2.16?!  Reverting.
> Revert "Allow jackson-module-jaxb-annotations to tolerate 2.2,3 in Import-Package"

- android-record/src/main/java/com/fasterxml/jackson/module/androidrecord/AndroidRecordModule.java
Fixes #251.
This PR adds a method to AndroidRecordModule that fixes/resolves GenericArrayTypes and ParameterizedTypes returned by Android reflection on method/constructor parameters. In turn, they behave the same as field types and constructor recognition on records that use both arrays and generic types no longer fails.
The type resolution method is compatible with the one in Android here: https://android.googlesource.com/platform/libcore/+/refs/heads/main/luni/src/main/java/libcore/reflect/ParameterizedTypeImpl.java#75
with the difference that it automatically resolves arrays fully where possible instead of returning an instance of GenericArrayType even on non-generic arrays (which causes errors in the current behaviour).
> android-record: Adapt generic types returned by Android reflection to follow Java behavior

- afterburner/src/main/java/tools/jackson/module/afterburner/deser/BeanPropertyMutator.java
- afterburner/src/main/java/tools/jackson/module/afterburner/deser/DelegatingPropertyMutator.java
- afterburner/src/main/java/tools/jackson/module/afterburner/deser/PropertyMutatorCollector.java
- afterburner/src/main/java/tools/jackson/module/afterburner/deser/SettableBooleanFieldProperty.java
- afterburner/src/main/java/tools/jackson/module/afterburner/deser/SettableBooleanMethodProperty.java
- afterburner/src/main/java/tools/jackson/module/afterburner/deser/SettableIntFieldProperty.java
- afterburner/src/main/java/tools/jackson/module/afterburner/deser/SettableIntMethodProperty.java
- afterburner/src/main/java/tools/jackson/module/afterburner/deser/SettableLongFieldProperty.java
- afterburner/src/main/java/tools/jackson/module/afterburner/deser/SettableLongMethodProperty.java
- afterburner/src/main/java/tools/jackson/module/afterburner/deser/SettableObjectFieldProperty.java
- afterburner/src/main/java/tools/jackson/module/afterburner/deser/SettableObjectMethodProperty.java
- afterburner/src/main/java/tools/jackson/module/afterburner/deser/SettableStringFieldProperty.java
- afterburner/src/main/java/tools/jackson/module/afterburner/deser/SettableStringMethodProperty.java
- afterburner/src/main/java/tools/jackson/module/afterburner/ser/PropertyAccessorCollector.java
- afterburner/src/main/java/tools/jackson/module/afterburner/util/bytebuddy/AbstractCreateLocalVarStackManipulation.java
- afterburner/src/main/java/tools/jackson/module/afterburner/util/bytebuddy/AbstractPropertyStackManipulation.java
- afterburner/src/main/java/tools/jackson/module/afterburner/util/bytebuddy/UsingIfStackManipulation.java
- afterburner/src/main/java/tools/jackson/module/afterburner/util/bytebuddy/UsingSwitchStackManipulation.java
(NOTE: not yet working)
As initial change to comply with newly added argument to `SettableBeanProperty.set()` (first arg, `DeserializationContext`) we pass just `null`. But ideally we would pass context through to generated mutator which might want to use it. This addition only applies to Jackson 3.0.
> Fix to pass DeserializationContext along with Afterburner set calls

- afterburner/src/test/java/tools/jackson/module/afterburner/deser/TestCreators2.java
- afterburner/src/test/java/tools/jackson/module/afterburner/deser/convert/CoerceJDKScalarsTest.java
- afterburner/src/test/java/tools/jackson/module/afterburner/deser/convert/CoerceStringToIntsTest.java
- afterburner/src/test/java/tools/jackson/module/afterburner/deser/convert/CoerceToBooleanTest.java
- afterburner/src/test/java/tools/jackson/module/afterburner/deser/convert/TestFailOnPrimitiveFromNullDeserialization.java
- afterburner/src/test/java/tools/jackson/module/afterburner/deser/filter/NullConversionsForContentTest.java
- afterburner/src/test/java/tools/jackson/module/afterburner/deser/jdk/JDKScalarsDeserTest.java
- afterburner/src/test/java/tools/jackson/module/afterburner/deser/merge/ArrayMergeTest.java
- afterburner/src/test/java/tools/jackson/module/afterburner/deser/struct/ScalarCoercionTest.java
- afterburner/src/test/java/tools/jackson/module/afterburner/roundtrip/BiggerDataTest.java
- blackbird/src/test/java/tools/jackson/module/blackbird/deser/TestCreators2.java
- blackbird/src/test/java/tools/jackson/module/blackbird/deser/convert/CoerceJDKScalarsTest.java
- blackbird/src/test/java/tools/jackson/module/blackbird/deser/convert/CoerceStringToIntsTest.java
- blackbird/src/test/java/tools/jackson/module/blackbird/deser/convert/CoerceToBooleanTest.java
- blackbird/src/test/java/tools/jackson/module/blackbird/deser/convert/TestFailOnPrimitiveFromNullDeserialization.java
- blackbird/src/test/java/tools/jackson/module/blackbird/deser/filter/NullConversionsForContentTest.java
- blackbird/src/test/java/tools/jackson/module/blackbird/deser/jdk/JDKScalarsDeserTest.java
- blackbird/src/test/java/tools/jackson/module/blackbird/deser/merge/ArrayMergeTest.java
- blackbird/src/test/java/tools/jackson/module/blackbird/deser/struct/ScalarCoercionTest.java
- blackbird/src/test/java/tools/jackson/module/blackbird/roundtrip/BiggerDataTest.java
Resolves failing tests affected by https://github.com/FasterXML/jackson-databind/issues/4858
> [`master`] fix failing tests after `FAIL_ON_NULL_FOR_PRIMITIVES` to `true` [databind#4890]

- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/util/failure/JacksonTestFailureExpected.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/util/failure/JacksonTestFailureExpectedInterceptor.java
- afterburner/src/test/java/com/fasterxml/jackson/module/afterburner/util/failure/JacksonTestShouldFailException.java
- android-record/src/test/java/com/fasterxml/jackson/module/androidrecord/testutil/failure/JacksonTestFailureExpected.java
- android-record/src/test/java/com/fasterxml/jackson/module/androidrecord/testutil/failure/JacksonTestFailureExpectedInterceptor.java
- android-record/src/test/java/com/fasterxml/jackson/module/androidrecord/testutil/failure/JacksonTestShouldFailException.java
- blackbird/src/test/java/com/fasterxml/jackson/module/blackbird/testutil/failure/JacksonTestFailureExpected.java
- blackbird/src/test/java/com/fasterxml/jackson/module/blackbird/testutil/failure/JacksonTestFailureExpectedInterceptor.java
- blackbird/src/test/java/com/fasterxml/jackson/module/blackbird/testutil/failure/JacksonTestShouldFailException.java
- jakarta-xmlbind/src/test/java/com/fasterxml/jackson/module/jakarta/xmlbind/testutil/failure/JacksonTestFailureExpected.java
- jakarta-xmlbind/src/test/java/com/fasterxml/jackson/module/jakarta/xmlbind/testutil/failure/JacksonTestFailureExpectedInterceptor.java
- jakarta-xmlbind/src/test/java/com/fasterxml/jackson/module/jakarta/xmlbind/testutil/failure/JacksonTestShouldFailException.java
- jaxb/src/test/java/com/fasterxml/jackson/module/jaxb/testutil/failure/JacksonTestFailureExpected.java
- jaxb/src/test/java/com/fasterxml/jackson/module/jaxb/testutil/failure/JacksonTestFailureExpectedInterceptor.java
- jaxb/src/test/java/com/fasterxml/jackson/module/jaxb/testutil/failure/JacksonTestShouldFailException.java
- paranamer/src/test/java/com/fasterxml/jackson/module/paranamer/testutil/failure/JacksonTestFailureExpected.java
- paranamer/src/test/java/com/fasterxml/jackson/module/paranamer/testutil/failure/JacksonTestFailureExpectedInterceptor.java
- paranamer/src/test/java/com/fasterxml/jackson/module/paranamer/testutil/failure/JacksonTestShouldFailException.java
> [JSTEP-10] Only add testutils to where needed

- afterburner/pom.xml
- android-record/pom.xml
- blackbird/pom.xml
- guice/pom.xml
- guice7/pom.xml
- jakarta-xmlbind/pom.xml
- jaxb/pom.xml
- mrbean/pom.xml
- no-ctor-deser/pom.xml
- osgi/pom.xml
- paranamer/pom.xml
- pom.xml
See: https://github.com/FasterXML/jackson-bom/pull/85
Fixes: https://github.com/FasterXML/jackson-databind/issues/4985 for all Modules in this repository
> [gradle-module-metadata-maven-plugin] update to version 1.0
